version: "3.9"
services:
  webserver:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    environment:
      - POSTGRES_ADDR=postgres
      - FLASK_ENV=docker
    ports:
      - "8000:8000"
  database:
    container_name: postgres
    image: postgres:13-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_volume:/var/lib/postgresql
volumes:
  db_volume: