"""empty message

Revision ID: 89fbdbf030e8
Revises: d8b04eea206e
Create Date: 2022-01-13 21:33:51.166516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89fbdbf030e8'
down_revision = 'd8b04eea206e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Items', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Items', 'price',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('Items', 'weight',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('Items', 'quantity',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Items', 'quantity',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('Items', 'weight',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('Items', 'price',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('Items', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
