"""empty message

Revision ID: d8b04eea206e
Revises: c1c7346728d7
Create Date: 2022-01-13 21:18:59.717322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b04eea206e'
down_revision = 'c1c7346728d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Items', sa.Column('quantity', sa.BigInteger(), nullable=True))
    op.add_column('Items', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('Items', 'product_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Items', sa.Column('product_code', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('Items', 'description')
    op.drop_column('Items', 'quantity')
    # ### end Alembic commands ###
